### ISSUE TITLE
webpack4 tree-shaking fail with version 2.25.1

### ISSUE THREAD

**Issue by maplor** [pmndrs/three-stdlib#287] opened 2023-09-14 11:19 UTC
- `three-stdlib` version: 2.25.1

### Problem description:

I use @react-three/drei for my 3D Scene in a webpack 4 project. after update three-stdlib version 2.25.1, I found that all  three-stdlib.js build in the bundle. but it's ok (tree-shaking) in version 2.25.0

### Suggested solution:

I found some change in this commit https://github.com/pmndrs/three-stdlib/commit/644d2adc9a58f477895d990d84f0b9d772397d94 

if this is realy a bug ?

**Comment by JaimeTorrealba** [comment] 2023-09-20 16:03
Same problem in TresjsCientos (we use vite)

![image](https://github.com/pmndrs/three-stdlib/assets/63722373/60c52f80-a42f-4b40-bb7b-be9ad0b0a904)

**Comment by CodyJasonBennett** [comment] 2023-09-21 00:53
Reverted recent changes in #290 since we had bad downstream effects in-between. WRT tree-shaking, is that still an issue in the specific `2.26.2` version of three-stdlib?

**Comment by maplor** [comment] 2023-09-21 08:30
> Reverted recent changes in #290 since we had bad downstream effects in-between. WRT tree-shaking, is that still an issue in the specific `2.26.2` version of three-stdlib?

It seen no change
![image](https://github.com/pmndrs/three-stdlib/assets/5591805/99e1fee3-4e9c-414f-9f63-5b9849916d39)

**Comment by CodyJasonBennett** [comment] 2023-09-23 00:48
I have #291 which vendors the affected dependency. Could you test with the following:

```js
{
  "dependencies": {
    "three-stdlib": "https://pkg.csb.dev/pmndrs/three-stdlib/commit/3bd54dfe/three-stdlib"
  }
}
```

**Comment by DmitryUlyanov** [comment] 2023-09-25 14:51
Still present with version `2.26.6`

**Comment by CodyJasonBennett** [comment] 2023-09-25 17:51
Can you share a reproduction or how you're encountering this?

**Comment by DmitryUlyanov** [comment] 2023-09-26 06:00
Sure, please find attached. 

To run: 
```
npx nx run test-treeshake:build --configuration=production
```
[test-tree-shake.zip](https://github.com/pmndrs/three-stdlib/files/12723311/test-tree-shake.zip)

See this line.
![image](https://github.com/pmndrs/three-stdlib/assets/6727524/b373e29f-4b5d-4856-bc18-4c43bce346d4)

With `three-stdlib` 1.14mb:
![image](https://github.com/pmndrs/three-stdlib/assets/6727524/14eb752b-703f-4a42-9bbc-63a393c8979d)

With `three/examples`, it's 700kb. 
![image](https://github.com/pmndrs/three-stdlib/assets/6727524/0a04cce6-b716-4f00-b9bf-986ea18b5253)

In my project the overhead is higher.

**Comment by DmitryUlyanov** [comment] 2023-09-26 06:20
And I just noticed on the screenshots this, but I actually did not import exporter anywhere. 
![image](https://github.com/pmndrs/three-stdlib/assets/6727524/ba00e3e3-9e86-4a68-b4d3-0d405e743a81)

**Comment by CodyJasonBennett** [comment] 2023-09-26 06:51
I wasn't able to run the attached test suite due to missing dependencies/config, but I was able to narrow down potential issues I've fixed in v2.26.7. Can you confirm on your end that this tree-shakes precisely to `GLTFLoader`? Chevrotain I couldn't find anything on since we vendor it to be pure.

**Comment by DmitryUlyanov** [comment] 2023-09-26 07:02
Updated the zip, forgot to include hidden files. 

[test-treeshake2.zip](https://github.com/pmndrs/three-stdlib/files/12723834/test-treeshake2.zip)

With 2.26.7 I get 
![image](https://github.com/pmndrs/three-stdlib/assets/6727524/44ae5eeb-6e94-42d3-a164-4b52ef34fd76)

**Comment by alvarosabu** [comment] 2023-10-17 08:50
Hey there, it might not be only webpack, with vite and `v2.26.0` the latest release of `@tresjs/cientos` was tripled https://bundlephobia.com/package/@tresjs/cientos@3.5.0 https://github.com/Tresjs/cientos/issues/254

![Screenshot 2023-10-17 at 10 46 05](https://github.com/pmndrs/three-stdlib/assets/4699008/c1514020-a725-4af6-880e-09f3b7e2b2dd)

**Comment by CodyJasonBennett** [comment] 2023-10-17 09:35
I have no observability unless you use the latest version. We ship sourcemaps and no longer consume most libraries from NPM by blind chance that helps here since I've received no feedback and cannot reproduce as such. On that note, I additionally have #306 which may crudely help here.

```js
{
  "dependencies": {
    "three-stdlib": "https://pkg.csb.dev/pmndrs/three-stdlib/commit/69f0da84/three-stdlib"
  }
}
```

**Comment by alvarosabu** [comment] 2023-10-17 11:51
@CodyJasonBennett just updated to `v2.27.3` bundle-size back to normal, at least with vite 👍

<img width="1201" alt="Screenshot 2023-10-17 at 13 49 48" src="https://github.com/pmndrs/three-stdlib/assets/4699008/1c8a09d5-1e5e-4069-956e-132174c51626">

**Closed** 2023-10-17 12:49 UTC
Labels: bug, released
