### ISSUE TITLE
FramebufferTexture is not exported from 'three'

### ISSUE THREAD

**Issue by adwulfran** [pmndrs/three-stdlib#126] opened 2022-01-31 10:27 UTC
- `three` version: three@0.131.3
- `three-stdlib` version: three-stdlib@2.6.1

### Problem description:

![Screenshot from 2022-01-31 11-14-53](https://user-images.githubusercontent.com/38992867/151775724-da05210d-f8d7-463a-8596-73635253d43b.png)

**Comment by bjornstar** [comment] 2022-01-31 10:34
This is a duplicate of #123 

Make sure your version of `@types/three` and `three` are for the same version.

**Closed by bjornstar** 2022-01-31 10:34 UTC
Labels: bug
