### ISSUE TITLE
Update Chevrotain to 10.1.1

### ISSUE THREAD

**Issue by ajnozari** [pmndrs/three-stdlib#133] opened 2022-02-28 19:36 UTC
### Describe the feature you'd like:

Chevrotain ^9.0.0 is missing source map files.  Bumping to 10.1.1 would resolve this dependency issue.

### Suggested implementation:

bump chevrotain to ^10.0.0 which includes the missing maps.

See this issue [chevrotain/chevrotain: Missing map dependency](https://github.com/Chevrotain/chevrotain/issues/1773)

**Comment by bd82** [comment] 2022-02-28 22:06
See breaking changes in 10.x
- https://chevrotain.io/docs/changes/BREAKING_CHANGES.html

**Comment by ChrisCrossCrash** [comment] 2022-03-01 09:35
I'm also having this problem. For a reproducible example and detailed explanation, see: https://github.com/Chevrotain/chevrotain/issues/1775. The the issue in Chevrotain has been closed since it has apparently been fixed in newer versions.

**Closed** 2022-03-01 10:04 UTC
Labels: enhancement
